# 共通設定
quarkus.datasource.username=myuser
quarkus.datasource.password=mypassword

# 開発用設定（組み込みH2）
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:todo_db;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.log.level=DEBUG
quarkus.log.category."com.mycompany.myapp".level=DEBUG
quarkus.log.console.json=true

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.parameters=true

quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE