# 共通設定
quarkus.datasource.username=myuser
quarkus.datasource.password=mypassword

# 開発用設定（組み込みH2）
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:todo_db;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.log.level=DEBUG
quarkus.log.category."com.mycompany.myapp".level=DEBUG
quarkus.log.console.json=true

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.parameters=true

quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE

# 認証・認可設定
## /login は認証不要
quarkus.http.auth.permission.public.paths=auth/login,/sample
quarkus.http.auth.permission.public.policy=permit

## その他のパスは JWT が必須
quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated

smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.verify.key.location=publicKey.pem
smallrye.jwt.issuer=http://localhost:8080

# 本番用設定（PostgreSQL）
# %prod.quarkus.datasource.db-kind=postgresql
# %prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/todo_db
# %prod.quarkus.hibernate-orm.database.generation=update